---

sudo: required

dist: trusty

language: generic

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible

install:
  - sudo ansible-galaxy install -r .roles.yml

script:
  - sudo ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - sudo ansible-playbook tests/test.yml -i tests/hosts
  - sudo ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
